apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders13
  template:
    metadata:
      labels:
        app: orders13
    spec:
      containers:
        - image: marafiievychmariia/orders14
          name: orders13
          ports:
            - containerPort: 8084
              name: orders13
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://192.168.0.177:5434/"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USERNAME
              value: "postgres"