apiVersion: v1
kind: Service
metadata:
  name: order-service-new
spec:
  type: ClusterIP
  ports:
    - name: "order-service-new"
      port: 8084
      targetPort: 8084
  selector:
    app: order-service-new
